global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "n8n"
    static_configs:
      - targets: ["n8n:5678"]
